### ISSUE TITLE
Webpack fails

### ISSUE THREAD

**Issue by RezaNeg** [deepavn/angular4-shopping-cart#1]
Hi, I tried to run your project but I got this error after ng serve:

`chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 100 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 204 kB {inline} [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 155 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 133 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.95 MB [initial] [rendered]

ERROR in ./app/app.component.ts
Module not found: Error: Can't resolve './app.component.css' in 'C:\angular4-shopping-cart-master\src\app'
resolve './app.component.css' in 'C:\angular4-shopping-cart-master\src\app'
  using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app)
    using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app/app.component.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.css doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.css.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.css.js doesn't exist
      as directory
        C:\angular4-shopping-cart-master\src\app\app.component.css doesn't exist
[C:\angular4-shopping-cart-master\src\app\app.component.css]
[C:\angular4-shopping-cart-master\src\app\app.component.css.ts]
[C:\angular4-shopping-cart-master\src\app\app.component.css.js]
[C:\angular4-shopping-cart-master\src\app\app.component.css]
 @ ./app/app.component.ts 16:21-51
 @ ./app/app.module.ts
 @ ./main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./main.ts
ERROR in ./app/app.component.ts
Module not found: Error: Can't resolve './app.component.html' in 'C:\angular4-shopping-cart-master\src\app'
resolve './app.component.html' in 'C:\angular4-shopping-cart-master\src\app'
  using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app)
    using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app/app.component.html)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.html doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.html.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\app.component.html.js doesn't exist
      as directory
        C:\angular4-shopping-cart-master\src\app\app.component.html doesn't exist
[C:\angular4-shopping-cart-master\src\app\app.component.html]
[C:\angular4-shopping-cart-master\src\app\app.component.html.ts]
[C:\angular4-shopping-cart-master\src\app\app.component.html.js]
[C:\angular4-shopping-cart-master\src\app\app.component.html]
 @ ./app/app.component.ts 15:22-53
 @ ./app/app.module.ts
 @ ./main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./main.ts
ERROR in ./app/home/home.component.ts
Module not found: Error: Can't resolve './home.css' in 'C:\angular4-shopping-cart-master\src\app\home'
resolve './home.css' in 'C:\angular4-shopping-cart-master\src\app\home'
  using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app/home)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app/home)
    using description file: C:\angular4-shopping-cart-master\package.json (relative path: ./src/app/home/home.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\home\home.css doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\home\home.css.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\angular4-shopping-cart-master\src\app\home\home.css.js doesn't exist
      as directory
        C:\angular4-shopping-cart-master\src\app\home\home.css doesn't exist
[C:\angular4-shopping-cart-master\src\app\home\home.css]
[C:\angular4-shopping-cart-master\src\app\home\home.css.ts]
[C:\angular4-shopping-cart-master\src\app\home\home.css.js]
[C:\angular4-shopping-cart-master\src\app\home\home.css]
 @ ./app/home/home.component.ts 18:21-42
 @ ./app/home/index.ts
 @ ./app/app.module.ts
 @ ./main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./main.ts

webpack: Failed to compile.
`
Could you please take a look at the error I got and help?

Thanks

**Comment by deepavn** [comment]
app\app.component.html
app\app.component.css
home\home.css

These three files are empty files in my project. 
I did not realize that github did not load them when I uploaded the files.

I added these files again. Please either download the project again or just create empty files in your project.
